// 部署マスタ (フィルタ用)
export const DEPARTMENTS: string[] = ["営業部", "開発部", "人事部", "情報システム部"]

// 社員データの型定義
export type Employee = {
  id: number
  employeeId: string
  name: string
  department: string
  employmentType: "新卒" | "中途"
  hireDate: string // ISO形式 (例: '2020-04-01')
  address: string
  birthDate: string
  qualifications: string[]
  phone?: string
  emergencyContact?: string
  bloodType?: "A" | "B" | "O" | "AB"
  gender?: "男性" | "女性" | "その他"
  hobbies?: string[]
  selfIntro?: string
  position?: string // 役職
  grade?: string // 社員グレード/等級
  manager?: string // 上長氏名
  employmentStatus?: "在籍" | "休職" | "退職予定"
  workLocation?: string // 勤務地/拠点
  skills?: string[] // 主なスキル
}

// 社員データ本体
export const EMPLOYEES: Employee[] = [
  {
    id: 1,
    employeeId: "E1001",
    name: "山田 太郎",
    department: "営業部",
    employmentType: "新卒",
    hireDate: "2020-04-01",
    address: "東京都新宿区西新宿2-8-1",
    birthDate: "1997-05-10",
    qualifications: ["TOEIC 800点", "普通自動車免許"],
    phone: "080-1234-1001",
    emergencyContact: "母: 090-5555-2222",
    bloodType: "A",
    gender: "男性",
    hobbies: ["ランニング", "コーヒー巡り"],
    selfIntro: "法人営業を担当。顧客課題ヒアリングが得意です。",
    position: "主任",
    grade: "G3",
    manager: "部長 田中健",
    employmentStatus: "在籍",
    workLocation: "東京本社",
    skills: ["営業戦略", "プレゼン", "Excel"],
  },
  {
    id: 2,
    employeeId: "E1002",
    name: "佐藤 花子",
    department: "開発部",
    employmentType: "中途",
    hireDate: "2022-11-01",
    address: "神奈川県横浜市中区日本大通1",
    birthDate: "1995-02-15",
    qualifications: ["基本情報技術者", "応用情報技術者"],
    phone: "080-1234-1002",
    emergencyContact: "父: 080-7777-1111",
    bloodType: "O",
    gender: "女性",
    hobbies: ["読書", "料理"],
    selfIntro: "フロントエンド全般を担当。UI/UX改善が好きです。",
    position: "シニアエンジニア",
    grade: "G4",
    manager: "開発部長 高井亮",
    employmentStatus: "在籍",
    workLocation: "東京本社",
    skills: ["React", "TypeScript", "UI設計"],
  },
  {
    id: 3,
    employeeId: "E1003",
    name: "鈴木 一郎",
    department: "開発部",
    employmentType: "新卒",
    hireDate: "2024-04-01",
    address: "埼玉県さいたま市浦和区高砂3-15-1",
    birthDate: "2001-08-30",
    qualifications: [],
    phone: "080-1234-1003",
    emergencyContact: "兄: 080-9999-0000",
    bloodType: "B",
    gender: "男性",
    hobbies: ["ゲーム", "写真"],
    selfIntro: "研修中。バックエンドも触りたいフロント志望。",
    position: "ジュニアエンジニア",
    grade: "G1",
    manager: "開発部長 高井亮",
    employmentStatus: "在籍",
    workLocation: "東京本社",
    skills: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: 4,
    employeeId: "E1004",
    name: "高橋 裕子",
    department: "営業部",
    employmentType: "中途",
    hireDate: "2021-06-15",
    address: "東京都渋谷区渋谷2-21-1",
    birthDate: "1992-09-12",
    qualifications: ["日商簿記2級"],
    phone: "080-1234-1004",
    emergencyContact: "夫: 070-2222-3333",
    bloodType: "AB",
    gender: "女性",
    hobbies: ["ピラティス"],
    selfIntro: "提案型営業と数値分析が得意です。",
    position: "係長",
    grade: "G3",
    manager: "部長 田中健",
    employmentStatus: "在籍",
    workLocation: "東京本社",
    skills: ["会計知識", "CRM", "提案書作成"],
  },
  {
    id: 5,
    employeeId: "E1005",
    name: "和田 純弥",
    department: "開発部",
    employmentType: "中途",
    hireDate: "2020-08-01",
    address: "大阪府南河内郡",
    birthDate: "1992-03-17",
    qualifications: ["簿記2級", "応用情報技術者", "AWS認定ソリューションアーキテクト"],
    phone: "080-1234-1005",
    emergencyContact: "妻: 080-4545-6767",
    bloodType: "A",
    gender: "男性",
    hobbies: ["卓球"],
    selfIntro: "このシステムの開発者です",
    position: "DevOps チームサブリーダー",
    grade: "全国教育大学卓球大会 シングルス3回戦負け、ダブルスベスト16",
    manager: "水谷隼",
    employmentStatus: "在籍",
    workLocation: "大阪支社",
    skills: ["フォアドライブ", "YGサーブ"],
  },
  {
    id: 6,
    employeeId: "E1006",
    name: "松本 京子",
    department: "人事部",
    employmentType: "新卒",
    hireDate: "2023-04-01",
    address: "大阪府大阪市北区梅田3-1-1",
    birthDate: "2000-07-22",
    qualifications: ["TOEIC 730点"],
    phone: "080-1234-1006",
    emergencyContact: "父: 080-2222-1111",
    bloodType: "A",
    gender: "女性",
    hobbies: ["映画鑑賞"],
    selfIntro: "採用アシスタントとして面接調整を担当。",
    position: "スタッフ",
    grade: "G1",
    manager: "人事部長 三浦恵",
    employmentStatus: "在籍",
    workLocation: "大阪支社",
    skills: ["調整力", "英語", "コミュニケーション"],
  },
  {
    id: 7,
    employeeId: "E1007",
    name: "渡辺 大樹",
    department: "営業部",
    employmentType: "新卒",
    hireDate: "2022-04-01",
    address: "愛知県名古屋市中区三の丸1-1-1",
    birthDate: "1999-03-18",
    qualifications: [],
    phone: "080-1234-1007",
    emergencyContact: "母: 080-3333-4444",
    bloodType: "B",
    gender: "男性",
    hobbies: ["サッカー"],
    selfIntro: "インサイドセールスで新規獲得に注力。",
    position: "スタッフ",
    grade: "G2",
    manager: "課長 川村徹",
    employmentStatus: "在籍",
    workLocation: "名古屋営業所",
    skills: ["リード獲得", "電話営業"],
  },
  {
    id: 8,
    employeeId: "E1008",
    name: "中村 美咲",
    department: "開発部",
    employmentType: "新卒",
    hireDate: "2023-04-01",
    address: "北海道札幌市中央区北2条西4丁目",
    birthDate: "2000-12-05",
    qualifications: ["基本情報技術者"],
    phone: "080-1234-1008",
    emergencyContact: "姉: 080-1212-3434",
    bloodType: "AB",
    gender: "女性",
    hobbies: ["散歩", "イラスト"],
    selfIntro: "UIコンポーネント整備に携わっています。",
    position: "ジュニアエンジニア",
    grade: "G1",
    manager: "開発部長 高井亮",
    employmentStatus: "在籍",
    workLocation: "札幌リモート",
    skills: ["React", "デザインシステム"],
  },
  {
    id: 9,
    employeeId: "E1009",
    name: "石井 亮介",
    department: "営業部",
    employmentType: "中途",
    hireDate: "2018-10-01",
    address: "福岡県福岡市中央区天神1-1-1",
    birthDate: "1986-04-27",
    qualifications: ["宅地建物取引士"],
    phone: "080-1234-1009",
    emergencyContact: "妻: 090-8888-9999",
    bloodType: "O",
    gender: "男性",
    hobbies: ["ランニング"],
    selfIntro: "地方拠点の大型案件を担当。",
    position: "課長",
    grade: "G4",
    manager: "部長 田中健",
    employmentStatus: "在籍",
    workLocation: "福岡支社",
    skills: ["大型提案", "契約交渉"],
  },
  {
    id: 10,
    employeeId: "E1010",
    name: "小林 里奈",
    department: "人事部",
    employmentType: "中途",
    hireDate: "2020-01-06",
    address: "京都府京都市下京区東塩小路町",
    birthDate: "1993-06-11",
    qualifications: ["社会保険労務士"],
    phone: "080-1234-1010",
    emergencyContact: "母: 080-5656-7878",
    bloodType: "A",
    gender: "女性",
    hobbies: ["寺社巡り"],
    selfIntro: "制度設計と労務管理を担当しています。",
    position: "リーダー",
    grade: "G3",
    manager: "人事部長 三浦恵",
    employmentStatus: "在籍",
    workLocation: "京都サテライト",
    skills: ["労務管理", "制度設計"],
  },
  {
    id: 11,
    employeeId: "E1011",
    name: "森田 健",
    department: "開発部",
    employmentType: "中途",
    hireDate: "2021-09-01",
    address: "茨城県水戸市三の丸1-4-1",
    birthDate: "1990-02-08",
    qualifications: ["LPIC Level1", "Pythonエンジニア認定基礎"],
    phone: "080-1234-1011",
    emergencyContact: "父: 070-1212-5656",
    bloodType: "B",
    gender: "男性",
    hobbies: ["DIY", "カラオケ"],
    selfIntro: "インフラと自動化スクリプトを担当。",
    position: "エンジニア",
    grade: "G3",
    manager: "CTO 小泉翔",
    employmentStatus: "在籍",
    workLocation: "東京本社",
    skills: ["Linux", "CI/CD", "Python"],
  },
  {
    id: 12,
    employeeId: "E1012",
    name: "藤田 彩",
    department: "営業部",
    employmentType: "新卒",
    hireDate: "2024-04-01",
    address: "宮城県仙台市青葉区本町3-8-1",
    birthDate: "2001-01-14",
    qualifications: [],
    phone: "080-1234-1012",
    emergencyContact: "父: 080-6767-4545",
    bloodType: "AB",
    gender: "女性",
    hobbies: ["写真", "旅行"],
    selfIntro: "新規アポイント獲得に挑戦中。",
    position: "スタッフ",
    grade: "G1",
    manager: "課長 川村徹",
    employmentStatus: "在籍",
    workLocation: "仙台営業所",
    skills: ["メールマーケ", "SNS"],
  },
  {
    id: 13,
    employeeId: "E1013",
    name: "青木 直樹",
    department: "開発部",
    employmentType: "中途",
    hireDate: "2017-07-03",
    address: "広島県広島市中区国泰寺町1-6-34",
    birthDate: "1985-05-19",
    qualifications: ["応用情報技術者", "Oracle Bronze"],
    phone: "080-1234-1013",
    emergencyContact: "妻: 080-9898-5656",
    bloodType: "O",
    gender: "男性",
    hobbies: ["ジョギング", "ガーデニング"],
    selfIntro: "レガシー資産のモダナイズを推進。",
    position: "シニアエンジニア",
    grade: "G4",
    manager: "CTO 小泉翔",
    employmentStatus: "在籍",
    workLocation: "広島リモート",
    skills: ["Java", "DB設計", "リファクタリング"],
  },
]
